### PR TITLE
Support for max_resque_workers

### PR DESCRIPTION
**Pull request by jcstringer**
Adds support for an optional configuration option of a max number of Resque workers to scale up to.

### CODE REVIEW

**Comment by davidw** [comment]
@jcstringer maybe you could simplify a bit of the logic by returning `Float::INFINITY` rather than nil ?

**Comment by variousred** [comment]
i thought this already supported this

**Comment by variousred** [comment]
nevermind it was the hash i was thinking of.
why not change it so this hash can be a configuration option set up on app init?

https://github.com/G5/heroku_resque_autoscaler/blob/master/lib/heroku_resque_autoscaler.rb

**Comment by variousred** [comment]
Or if you need the per app instance configuration level still, at least hook into the scaling hash somehow still, it seems better than short circuiting

**Comment by johnmendonca** [comment]
@variousred not sure what you're talking about exactly, specifying a hash like `{ :workers => 2, :job_count => 15 }` in the config block?

I agree with @davidw though we could just set a hard limit of 5 which appears to be the current max.  Also, if this value is config'd to "foo" it will result in max workers == 0.

Going along with this do we need to spinup new apps with env var MAX_RESQUE_WORKERS=1 by default?  Otherwise it would need lot of manual changes that might get overlooked?  I'm going to be digging into the app-creator pipeline this week to use free dynos for caus (or just remove them), and to spinup cmses setup to deploy to aws by default.  I can include changes related to this if needed.

**Comment by variousred** [comment]
yes, @johnmendonca 
i was suggesting that the 
``` WORKER_SCALE = [
      { :workers => 1, :job_count => 1 },
      { :workers => 2, :job_count => 15 },
      { :workers => 3, :job_count => 25 },
      { :workers => 4, :job_count => 40 },
      { :workers => 5, :job_count => 60 }
    ]```
is the domain owner of how many workers get scaled an when. It makes sense to me that the logic for maximum number also lives here, and in fact already does inherently with a max of 5 by definition.

**Comment by johnmendonca** [comment]
@variousred Yeah i see how you could specify a value like `[{ workers: 1, job_count: 999}]` to override this default, but then we need a way to activate this for individual apps, not entire app types.  You would still need some kind of a true/false env var and that could still be considered a short circuit of sorts.  From an end user perspective the best thing would be a dyno type aware scaler but that sounds like a fair bit of complexity involving heroku api calls, better just look at sidekiq as a long term solution.  This PR is more like a quick fix to allow scaling to free dynos asap.

**Comment by johnmendonca** [comment]
:ship: :anchor:

**Comment by variousred** [comment]
looks great! :shipit:

**Pull request merged**
